s = 'TTGATGTCACTGAGATCAAATTGCGCGCAGACCATATCCTCCCCACATTACCTATCAATCCAGATGCTGCACTGTCTGCCCTGCCAACTTTAGGTTTTATTGACTTTGTATGGGGATCCCTGGCAGCCCGGGGGGTACACAAACGCTACCTAGACCTGCCATTGCGTGGCCACGCGGGCGGTTGCGGAACGATACAAGCAACGGATAGACTCCAAAATCTAGTACCCCACTAAATGGCAGGCTAGTGTCGGGAGGTCTAAAAGTGTACGTGTGTTAGAGCTCCGCTAGAGCGGGATGCCAATGCCGCTCCCGTGTTGCGACGAAGGAGATTTTATGTTTGGTTCATGACAAAGGGTATCCAGCAAGCGCGAGTATCCCGAAAATCAGTGTGGTTGTTAACTTGTAAGTGAATGGCAAGGCGGGACACCCGCAACCTCCGCAGTGTGCTATCTTGGTTGTCGCTGTCTCACCCCTGATCTTAAGTTCATACGTTGGGGCTGGAGGAGTACCCCGCATGACAGCGCGAGGTGTACCTGCGGAACTACGCGCATGTGACATAAGCATAAGCTAGCAACTT$TCCCAGGGTTCCCCATTGCATTCATACATAACAGGACCGCCCCCTCCTCTGGAATAGTCATTGACGTAAACGTACTGGCATGTACGTCAAAACCTTGGTTATAGTGTGGCGAAAAGGCATGAATTTCTTCGGTGAGAAGGGAAGTGTAGGCTAGATGTTGTTGTCCGAATGTAGGGCTGGCGCAAGCTCGCCTGAACGACTATAGCACCACTCGCGGGGTGCGGGTCGACCTGGCCGGCGTAAAGGTAAATGGGCAC'

def inverseBWT(s):
    table = ['' for i in range(len(s))]
    for i in range(len(s)):
        table = [s[i] + x for i,x in enumerate(table)]
        table.sort()
    for e in table:
        if e[-1] == '$':
            return e
    return

print(inverseBWT(s))